docker:
  services:
    - docker

- run: npm install:
  cache_directories:
    - "~/docker"
  - command:
    - docker info
    - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
    - docker build -t tester -f docker/tester_Dockerfile .
    - mkdir -p ~/docker; docker save tester > ~/docker/image.tar

run:
  - command:
    - docker run tester /bin/bash -li -c "CIRCLECI=true nose2"
